FROM python:3.12-bookworm

WORKDIR /fetch-users
COPY ./requirements.txt /fetch-users/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /fetch-users/requirements.txt
COPY ./ /fetch-users
COPY airflow.cfg /fetch-users/airflow.cfg
