FROM python:3.10-bookworm

# Устанавливаем рабочую директорию
WORKDIR /fetch-users

# Копируем зависимости и устанавливаем
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Копируем весь проект
COPY . .

# Указываем точку входа
ENTRYPOINT ["python3", "run.py"]
